---
title: "Intro to tidyverse and ggplot2 libraries"
output: html_notebook
---

```{r}
# To load Data
#library(tidyverse)
#carData = data("mtcars")
carData = read.csv('mtcars.csv')

#Print first 5 lines

#head(carData, 5)

#Structure of data
str(carData)

#show  the features (column names)
colnames(carData)

#print the number of samples rows and features (columns) in the dataframe

nrow(carData)
ncol(carData)
```


```{r}
#mutate used to add new columns or modify existing ones

#carData %>% mutate(cyltype = 'High') 

#carData %>% mutate(cyltype = ifelse(cyl > 6, 'High', 'Low'))

#carData %>% mutate(wtton = 0.45*wt)

#carData.new = carData %>% mutate(cyltype = ifelse(cyl > 6, 'High', 'Low'), wtton = 0.45*wt)

#str(carData.new)
#print(carData.new)

#carData.new %>% summarize(mean(wtton))
#carData.new %>% summarize(meanweight = mean(wtton)) #gives the variable name
#carData.new %>% summarize(mean(wtton), mean(disp))

#carData.new %>% group_by(cyltype) %>%
  #summarize(mean(wtton), mean(disp))

#carData.new %>% filter(wtton > 2)

#carData.new %>% filter(wtton > 2 & cyl > 4)

#carData.new %>% select(wtton, cyl)
carData.new %>% select(-wtton)

```


```{r}
#Initiate the ggplot() function binding to the data frame
ggplot(data = carData)

# Create a plot object

carplot = ggplot(data = carData)

carplot = ggplot(data = carData, aes(x = wt, y = disp))

carplot = carplot + geom_point()
carplot

carplot = carplot + labs(x = 'weight (1000 lbs)', y = 'Displaysment (cu. in)', title = 'Weight vs Displacements')
carplot
```



