---
title: "Multicollinearity Problem Tutorial in R"
author: "Bidyut Ghosh"
date: "`r Sys.Date()`"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,comment = NA, warning = FALSE,message = FALSE)
```

# Data Import

```{r}
library(readxl)
table10_8<-read_excel("Table 10_8.xls",skip = 3)
head(table10_8)
```


# Model Specifcation

$$ Y=\beta_1+\beta_2 X_2+\beta_3 X_3+\beta_4 X_4+\beta_5 X_5+u $$



# Data Visualisation for Collinearity

```{r}
library(corrplot)
corrplot(corr = cor(table10_8[,3:7]),type = "upper")
```

# Model Estimation

```{r}
model1<-lm(Y~X1+X2+X3+X4+X5,data = table10_8)
summary(model1)
```

# VIF Values

```{r}
library(car)
vif(model1)
```

# Model 2 Estimation

```{r}
model2<-lm(Y~X1+X3+X4+X5, data = table10_8)
summary(model2)
```
# VIF values of Model 2

```{r}
vif(model2)
```

# Model 3

```{r}
model3<-lm(Y~X1+X3+X4,data = table10_8)
summary(model3)
```

# VIF values of Model 3

```{r}
vif(model3)
```

